// Code generated by iotas dev. DO NOT EDIT.
package examples

import (
	"encoding/json"
	"fmt"
)

var ExtraTypeList = [...]string{
	One:   "One",
	Two:   "Two",
	Three: "Three",
}

var ExtraTypeMap = map[string]ExtraType{
	"One":   One,
	"Two":   Two,
	"Three": Three,
}

func (t ExtraType) String() string {
	return ExtraTypeList[t]
}

func (t ExtraType) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.String())
}

func (t *ExtraType) UnmarshalJSON(data []byte) error {
	var typeNameStr string
	if err := json.Unmarshal(data, &typeNameStr); err != nil {
		return err
	}

	id, ok := ExtraTypeMap[typeNameStr]
	if !ok {
		return fmt.Errorf("no mapping for the type: %s", typeNameStr)
	}

	*t = id

	return nil
}
