// Code generated by iotas dev. DO NOT EDIT.
package examples

import (
	"encoding/json"
	"fmt"
)

var MatrixTypeList = [...]string{
	Unknown: "Unknown",
	OLED:    "OLED",
	AMOLED:  "AMOLED",
	TFT:     "TFT",
}

var MatrixTypeMap = map[string]MatrixType{
	"Unknown": Unknown,
	"OLED":    OLED,
	"AMOLED":  AMOLED,
	"TFT":     TFT,
}

func (t MatrixType) String() string {
	return MatrixTypeList[t]
}

func (t MatrixType) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.String())
}

func (t *MatrixType) UnmarshalJSON(data []byte) error {
	var typeNameStr string
	if err := json.Unmarshal(data, &typeNameStr); err != nil {
		return err
	}

	id, ok := MatrixTypeMap[typeNameStr]
	if !ok {
		return fmt.Errorf("no mapping for the type: %s", typeNameStr)
	}

	*t = id

	return nil
}
